---
pipeline:
  $conforms-to: [org.codingmatters.poom.ci.pipeline.StageProvider]

  from:
    $list: $repositorySpec

  stages:
    $list: $stage

  onSuccess:
    $list: $stage
  onError:
    $list: $stage

  cleanup:
    $list: $stage

  env:
    $list:
      $value-object: org.codingmatters.value.objects.values.ObjectValue

  secrets:
    $list: $secret

stage:
  name: string
  timeout: long
  before: string
  after: string
  onlyWhen:
    $list: string
  exec:
    $list: string

stageHolder:
  stage: $stage
  type:
    $enum: MAIN, ERROR, SUCCESS, CLEANUP

secret:
  name: string
  content: string
  as:
    $enum: var, file

repositorySpec:
  url: string
  branch: string