version: '3'

services:

  github-webhook:
    image: ${codingmatters.docker.namespace}/poom-ci-github-webhook:${org.codingmatters.poom.ci:poom-ci-github-webhook:jar.version}
    ports:
      - 6543:9999
    environment:
      GITHUB_SECRET_TOKEN: 9a167bbea7e96c86fd87ae254f646cbea050ef63
      PIPELINE_API_URL: http://pipeline-service:9999/pipelines/v1

  pipeline-service:
    image: ${codingmatters.docker.namespace}/poom-ci-pipeline-service:${org.codingmatters.poom.ci:poom-ci-pipeline-service:jar.version}
    environment:
      JOB_REGISTRY_URL: http://poomjobs-registries-service:9999/poomjobs-jobs/v1
    ports:
      - 6545:9999

  poomjobs-registries-service:
    image: ${codingmatters.docker.namespace}/poomjobs-registries-service:${org.codingmatters.poom:poomjobs-registries-service:jar.version}
    ports:
      - 6544:9999

  maven-repository:
    image: ${codingmatters.docker.namespace}/archiva:${archiva.version}
    ports:
      - 8080:8080
    volumes:
      - archiva-conf:/var/archiva/conf
      - archiva-data:/var/archiva/data
      - archiva-logs:/var/archiva/logs
      - archiva-repositories:/var/archiva/repositories

volumes:
  archiva-conf:
  archiva-data:
  archiva-logs:
  archiva-repositories:


