storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/.htpasswd

packages:
  '@flexio-services/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  '*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

logs:
  - {type: file, path: verdaccio.log, level: info}

web:
  enable: true
  title: Verdaccio
  gravatar: true
  sort_packages: asc